import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Goal Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
         <head>
        <link rel='icon' href='https://www.svgrepo.com/svg/66257/goal' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
